// Code generated by tools/genpermissions. DO NOT EDIT.
package provider

// resourcePermissionsMarkdown maps Terraform resource type names to their
// required-permissions documentation, appended to each schema's MarkdownDescription.
var resourcePermissionsMarkdown = map[string]string{
	"chalk_aws_cloud_credentials":                                 "**Required permissions:** `project.create`",
	"chalk_azure_cloud_credentials":                               "**Required permissions:** `project.create`",
	"chalk_cluster_background_persistence":                        "**Required permissions:** `team.admin`, `deploy.read`",
	"chalk_cluster_background_persistence_deployment_binding":     "**Required permissions:** `project.create`",
	"chalk_cluster_gateway":                                       "**Required permissions:** `team.admin`, `deploy.read`",
	"chalk_cluster_gateway_binding":                               "**Required permissions:** `project.create`",
	"chalk_cluster_timescale":                                     "**Required permissions:** `team.admin`, `deploy.read`",
	"chalk_datasource":                                            "**Required permissions:** `secrets.write`, `secrets.decrypt`",
	"chalk_datasource_databricks":                                 "**Required permissions:** `secrets.write`, `secrets.decrypt`",
	"chalk_datasource_kafka":                                      "**Required permissions:** `secrets.write`, `secrets.decrypt`",
	"chalk_datasource_kinesis":                                    "**Required permissions:** `secrets.write`, `secrets.decrypt`",
	"chalk_datasource_postgresql":                                 "**Required permissions:** `secrets.write`, `secrets.decrypt`",
	"chalk_environment":                                           "**Required permissions:** `project.create`, `deploy.create`, `deploy.read`, `environment.create` *(team-scoped)*",
	"chalk_environment_background_persistence_deployment_binding": "**Required permissions:** `project.create`",
	"chalk_environment_gateway_binding":                           "**Required permissions:** `project.create`",
	"chalk_environment_offline_store_connection_binding":          "**Required permissions:** `deploy.create`, `deploy.read`",
	"chalk_gcp_cloud_credentials":                                 "**Required permissions:** `project.create`",
	"chalk_kubernetes_cluster":                                    "**Required permissions:** `project.create`",
	"chalk_managed_aws_vpc":                                       "**Required permissions:** `team.admin`, `project.create`",
	"chalk_managed_cluster":                                       "**Required permissions:** `project.create`",
	"chalk_managed_environment":                                   "**Required permissions:** `environment.create` *(team-scoped)*",
	"chalk_offline_store_connection":                              "**Required permissions:** `deploy.create`, `deploy.read`",
	"chalk_private_gateway_binding":                               "**Required permissions:** `project.create`",
	"chalk_project":                                               "**Required permissions:** `project.create` *(team-scoped)*",
	"chalk_service_token":                                         "**Required permissions:** `tokens.write`, `tokens.list`",
	"chalk_telemetry":                                             "**Required permissions:** `team.admin`, `deploy.read`",
	"chalk_telemetry_binding":                                     "**Required permissions:** `project.create`",
	"chalk_unmanaged_cluster_background_persistence":              "**Required permissions:** `team.admin`, `deploy.read`",
	"chalk_unmanaged_environment":                                 "**Required permissions:** `environment.create` *(team-scoped)*",
}

// datasourcePermissionsMarkdown maps Terraform data-source type names to their
// required-permissions documentation, appended to each schema's MarkdownDescription.
var datasourcePermissionsMarkdown = map[string]string{
	"chalk_environment": "**Required permissions:** `deploy.read`",
}
