// schemacompat detects breaking changes between two Terraform provider schemas
// generated by `terraform providers schema -json`.
//
// Usage: schemacompat <old-schema.json> <new-schema.json>
//
// Exits 0 if no breaking changes are found, 1 if breaking changes are detected.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: schemacompat <old-schema.json> <new-schema.json>")
		os.Exit(2)
	}

	old, err := loadSchema(os.Args[1])
	if err != nil {
		log.Fatalf("loading old schema %s: %v", os.Args[1], err)
	}
	cur, err := loadSchema(os.Args[2])
	if err != nil {
		log.Fatalf("loading new schema %s: %v", os.Args[2], err)
	}

	changes := Diff(old, cur)
	if len(changes) == 0 {
		fmt.Println("No breaking changes detected.")
		return
	}

	fmt.Fprintf(os.Stderr, "Found %d breaking change(s):\n\n", len(changes))
	for _, c := range changes {
		fmt.Fprintf(os.Stderr, "  %s\n", c)
	}
	os.Exit(1)
}

func loadSchema(path string) (*ProviderSchemaOutput, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading file: %w", err)
	}
	var out ProviderSchemaOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("parsing JSON: %w", err)
	}
	return &out, nil
}
